# .github/workflows/build-and-deploy.yml

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
        
      # a standard step for GitHub actions on Node
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v3
        with:
          # update the Node version to meet your needs
          node-version: 16
          cache: npm

      - name: Build
        run: |
          npm ci
          npm run build
          npm run export
          touch out/.nojekyll

      - name: Deploy
        # https://github.com/JamesIves/github-pages-deploy-action
        # /brandonbrown/HudsonDanielle_DWA_1.6exercise
        uses: brandonbrown/HudsonDanielle_DWA_1.6exercise@main
        with:
          branch: gh-pages
          folder: out